### ISSUE TITLE
[MATLAB] matlab tools are not referenced from path directory

### ISSUE THREAD

**Issue by bwijerat** [TsotsosLab/SMILER#10]
It appears that the matlab tools are not being referenced from the path directory, in order to run the matlab models I need to run smiler only from the smiler directory (even when placed in my path).

Smiler directory: `/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/ `
Current directory: `~/Pictures`

`smiler run -m "aim" ~/Pictures/input ~/Pictures/output`
```
************************************************************
*************************** AIM ****************************
************************************************************
Setting up model...
Running model...
Error using cd
Cannot CD to /home/bwijerat/Pictures/smiler_matlab_tools (Name is nonexistent or not a directory).

Traceback (most recent call last):
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler", line 272, in <module>
    cli()
  File "/home/bwijerat/.local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/bwijerat/.local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/bwijerat/.local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bwijerat/.local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bwijerat/.local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler", line 165, in run
    experiment.run()
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler_tools/smiler_tools/experiment.py", line 82, in run
    run.run(self._experiment_parameter_map)
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler_tools/smiler_tools/experiment.py", line 115, in run
    self._config_parameter_map, my_run_map)
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler_tools/smiler_tools/models.py", line 208, in run_batch
    startup_options=options_matlab_startup, init_iSMILER=True)
  File "/home/bwijerat/Documents/EECS6323/SMILER-v_1.1/smiler_tools/smiler_tools/utils.py", line 76, in maybe_init_matlab_engine
    eng.cd('smiler_matlab_tools')
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: Cannot CD to /home/bwijerat/Pictures/smiler_matlab_tools (Name is nonexistent or not a directory).
```

**Comment by tkunic** [comment]
Thanks for the report! It should be fixed on the v_1.1 branch.
