### ISSUE TITLE
[Docker] module 'urllib' has no attribute 'URLopener'

### ISSUE THREAD

**Issue by bwijerat** [TsotsosLab/SMILER#4]
Consistently getting this error when trying to run docker models from the CLI. 
Listed below are models that produce this error.

> Docker models: **DGII, DVAP, ICF, MLNet, SAM, SalGAN, eDN, oSALICON**

Only BMS worked. This was run with Python 3.6.

```
Setting up model...
Downloading and extracting model files:
    models/attention_final
    models/attention_test.prototxt
    models/model.mat
    models/train_val.prototxt
Traceback (most recent call last):
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler", line 272, in <module>
    cli()
  File "/home/bwijerat/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bwijerat/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bwijerat/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bwijerat/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bwijerat/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler", line 165, in run
    experiment.run()
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler_tools/smiler_tools/experiment.py", line 82, in run
    run.run(self._experiment_parameter_map)
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler_tools/smiler_tools/experiment.py", line 107, in run
    self._model.maybe_run_setup()
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler_tools/smiler_tools/models.py", line 91, in maybe_run_setup
    self._download_and_extract_model_files()
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler_tools/smiler_tools/models.py", line 100, in _download_and_extract_model_files
    urlopener = urllib.URLopener()
AttributeError: module 'urllib' has no attribute 'URLopener'
```
Searching for answers I found this post saying it's a Python 2+3 compatibility issue:
https://stackoverflow.com/questions/3969726/attributeerror-module-object-has-no-attribute-urlopen

But running the same models in Python 2.7 produced this error, even when click was installed.
```
Traceback (most recent call last):
  File "/media/bwijerat/WinStorage/bwijerat/Documents/LNX_DATA_SET/SMILER-master/smiler", line 11, in <module>
    import click
ImportError: No module named click
```
Let me know what you think. Thanks!

**Comment by tkunic** [comment]
Thanks for the issue! From the paths involved, this seems to be a problem in the anaconda environment. Unfortunately, I haven't had a chance to test the CLI with anaconda and develop instructions for that (I'll try and do so soon), but until then SMILER Docker models should work on Ubuntu after:

- Installing `nvidia-docker2` using their installation instructions.
- Installing click and yaml using `sudo apt install python-click python-yaml`.

In case you decide to go this route, make sure you run it in your global python environment (outside of anaconda and virtualenv).

**Comment by bwijerat** [comment]
Thanks, I retested it and it's working for all Docker models when using the global python environment

**Comment by matthias-k** [comment]
I think this is a python 2/3 issue. In python3, URLOpener is part of [urllib.request](https://docs.python.org/3/library/urllib.request.html#urllib.request.URLopener) and actually deprecated since python 3.3
