### ISSUE TITLE
model.zip file not found for DVAP, MLNet, eDN, and oSALICON

### ISSUE THREAD

**Issue by f-wright** [TsotsosLab/SMILER#46]
Running DVAP, MLNet, eDN, or oSALICON produces a file not found error on both my and @cfmcint's machines. 

The errors are very similar for all four models. Here is an example output for MLNet:
```
************************************************************
************************** MLNet ***************************
************************************************************
Setting up model...
Downloading and extracting model files:
    vgg16_weights.h5
    mlnet_salicon_weights.pkl
IOError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/fwright/SMILER/smiler", line 274, in <module>
    cli()
  File "/home/fwright/anaconda3/envs/smiler/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/fwright/anaconda3/envs/smiler/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/fwright/anaconda3/envs/smiler/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fwright/anaconda3/envs/smiler/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fwright/anaconda3/envs/smiler/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/fwright/SMILER/smiler", line 165, in run
    experiment.run()
  File "/home/fwright/SMILER/smiler_tools/smiler_tools/experiment.py", line 82, in run
    run.run(self._experiment_parameter_map)
  File "/home/fwright/SMILER/smiler_tools/smiler_tools/experiment.py", line 107, in run
    self._model.maybe_run_setup()
  File "/home/fwright/SMILER/smiler_tools/smiler_tools/models.py", line 94, in maybe_run_setup
    self._download_and_extract_model_files()
  File "/home/fwright/SMILER/smiler_tools/smiler_tools/models.py", line 110, in _download_and_extract_model_files
    os.remove(temp_file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpggf7yayq/model.zip'
```

**Comment by cfmcint** [comment]
oSALICON's path has been fixed and no longer experiences the model.zip not found error. The other model paths are still not working.
